### ISSUE TITLE
What if my angular.module('mathmodule', []) declaration is in another file?

### ISSUE THREAD

**Issue by rodgerpaulo** [curttimson/angularjs-jest-example#3]
supposing that my application structure is like this:

**app.js**

``` javascript
angular.module('mathmodule', [])
```
**math.service.js**

``` javascript
function MathService() {

  var addTwoNumbers = function (x, y) {
    return x + y;
  };
  return {
    addTwoNumbers
  };
}
angular.module('superag').factory('mathservice', MathService);
```

How do I define `mathservice` before run the test?

trying hard but getting this message:

``` ssh
[$injector:nomod] Module 'mathmodule' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.9/$injector/nomod?p0=mathmodule
```

**Comment by choudharypravesh03** [comment]
+1

**Comment by JuankS92** [comment]
Hi @rodgerpaulo, I see 2 different modules on the code you provided (`mathservice` and `superag`).
On the other hand, I had the same issue and it seems to be pretty clear after looking at [other examples](https://github.com/rantiev/template-jest-with-angular). The main module is not available when Jest runs the test. To solve the issue and make the math module available, in your package.json add

```
"jest": {
  "setupTestFrameworkScriptFile": "<rootDir>/jest.init.js"
}
```

which is the initial configuration for all your Jest tests, in there you can add the mathmodule

`angular.module('mathmodule', [])`

I think this example is pretty basic and does not cover other common scenarios like having controllers, directives and services on different folders. For those cases, we need to tell Jest to use some specific things before mocking the module and the controller. You can even add specific dependencies to test with your components in that init file.

**Comment by rodgerpaulo** [comment]
@JuankS92, Thanks for your attention. I'll try later and come back to report the result!

**Comment by curttimson** [comment]
@rodgerpaulo Did this fix your issue?

**Comment by rodgerpaulo** [comment]
@curttimson sorry for the delay. It works :+1:
